// Code generated by mockzilla-codegen. DO NOT EDIT.

package hello_world

import (
	"context"
	"encoding/json"
	"errors"
	"net/http"

	chi "github.com/go-chi/chi/v5"
	"github.com/mockzilla/mockzilla-codegen/pkg/runtime"
	"github.com/mockzilla/mockzilla-codegen/pkg/runtime/httpserver"
	"github.com/mockzilla/mockzilla-codegen/pkg/runtime/validation"
)

// Fails to compile when the runtime does not match the generator that wrote this file.
const _ = runtime.SupportsGeneratorV1

type PostHelloQuery struct {
	Q *string `json:"q,omitempty"`
}

type PostHelloRequestBody map[string]any

type PostHelloResponse200 struct {
	Hellow *string `json:"hellow,omitempty"`
}

// ServiceInterface is what the generated handlers call. Implement it with the business logic.
type ServiceInterface interface {
	// PostHello handles POST /hello.
	PostHello(ctx context.Context, opts *PostHelloServiceRequestOptions) (*PostHelloResponseData, error)
}

// PostHelloServiceRequestOptions is what PostHello receives.
type PostHelloServiceRequestOptions struct {
	Query *PostHelloQuery
	// Body sent as application/json.
	Body PostHelloRequestBody
	// GenerateResponse makes a mock response that satisfies the spec.
	GenerateResponse func() (*PostHelloResponseData, error)
	RawRequest       *http.Request
}

// Validate checks the parameters and the body against the constraints of the spec.
func (o *PostHelloServiceRequestOptions) Validate() error {
	return nil
}

// PostHelloResponseData is what PostHello returns.
type PostHelloResponseData struct {
	Status  int
	Headers http.Header
	Body    any

	contentType string
}

// NewPostHelloResponseData returns the 200 response with its application/json body.
func NewPostHelloResponseData(body *PostHelloResponse200) *PostHelloResponseData {
	return &PostHelloResponseData{Status: 200, Body: body, contentType: "application/json"}
}

// WithStatus sets the status code.
func (r *PostHelloResponseData) WithStatus(code int) *PostHelloResponseData {
	r.Status = code
	return r
}

// WithHeaders sets the headers.
func (r *PostHelloResponseData) WithHeaders(h http.Header) *PostHelloResponseData {
	r.Headers = h
	return r
}

// StatusCode returns the status.
func (r *PostHelloResponseData) StatusCode() int {
	return r.Status
}

// Header returns the headers.
func (r *PostHelloResponseData) Header() http.Header {
	return r.Headers
}

// Payload returns the body.
func (r *PostHelloResponseData) Payload() any {
	return r.Body
}

// ContentType returns the media type of the body, empty for the default of its Go type.
func (r *PostHelloResponseData) ContentType() string {
	return r.contentType
}

// The error types the handlers use, as the runtime declares them.
type (
	ErrorKind           = httpserver.ErrorKind
	HandlerError        = httpserver.HandlerError
	ErrorHandler        = httpserver.ErrorHandler
	ErrorHandlerFunc    = httpserver.ErrorHandlerFunc
	DefaultErrorHandler = httpserver.DefaultErrorHandler
)

// The kinds of HandlerError.
const (
	ErrorParse      = httpserver.ErrorParse
	ErrorDecode     = httpserver.ErrorDecode
	ErrorValidation = httpserver.ErrorValidation
	ErrorService    = httpserver.ErrorService
	ErrorResponse   = httpserver.ErrorResponse
)

var bodyPresence = runtime.Presence{
	IsChecked: true,
}

// ServerOptions is what the adapter and the router are set up with.
type ServerOptions struct {
	Router              any
	Middleware          []func(http.Handler) http.Handler
	OperationMiddleware []func(http.Handler) http.Handler
	ErrorHandler        httpserver.ErrorHandler
	JSONDecoder         func(data []byte, v any) error
	JSONEncoder         func(v any) ([]byte, error)
	MultipartMaxMemory  int64
	Presence            runtime.PresenceChecker
}

// ServerOption sets one field of ServerOptions.
type ServerOption func(*ServerOptions)

// NewServerOptions applies opts to the defaults.
func NewServerOptions(opts ...ServerOption) *ServerOptions {
	o := &ServerOptions{
		ErrorHandler:       httpserver.DefaultErrorHandler{},
		JSONDecoder:        json.Unmarshal,
		JSONEncoder:        json.Marshal,
		MultipartMaxMemory: 33554432,
		Presence:           bodyPresence,
	}
	for _, opt := range opts {
		opt(o)
	}
	return o
}

// WithMiddleware wraps the routes with mw, outermost first; on a new router, unknown paths too.
func WithMiddleware(mw ...func(http.Handler) http.Handler) ServerOption {
	return func(o *ServerOptions) {
		o.Middleware = append(o.Middleware, mw...)
	}
}

// WithOperationMiddleware wraps each operation with mw, once its name is on the context.
func WithOperationMiddleware(mw ...func(http.Handler) http.Handler) ServerOption {
	return func(o *ServerOptions) {
		o.OperationMiddleware = append(o.OperationMiddleware, mw...)
	}
}

// WithErrorHandler sets what writes the response of a failed request.
func WithErrorHandler(h httpserver.ErrorHandler) ServerOption {
	return func(o *ServerOptions) {
		o.ErrorHandler = h
	}
}

// WithJSONDecoder sets what reads JSON request bodies.
func WithJSONDecoder(decode func(data []byte, v any) error) ServerOption {
	return func(o *ServerOptions) {
		o.JSONDecoder = decode
	}
}

// WithJSONEncoder sets what writes JSON response bodies and stream frames.
func WithJSONEncoder(encode func(v any) ([]byte, error)) ServerOption {
	return func(o *ServerOptions) {
		o.JSONEncoder = encode
	}
}

// WithMultipartMaxMemory sets how much of a multipart form stays in memory.
func WithMultipartMaxMemory(n int64) ServerOption {
	return func(o *ServerOptions) {
		o.MultipartMaxMemory = n
	}
}

// WithPresence sets what checks the keys of request bodies and fills their defaults.
func WithPresence(p runtime.PresenceChecker) ServerOption {
	return func(o *ServerOptions) {
		o.Presence = p
	}
}

// HTTPAdapter answers HTTP requests by calling the service.
type HTTPAdapter struct {
	svc        ServiceInterface
	opts       *ServerOptions
	operations httpserver.Chain
}

type responseData interface {
	StatusCode() int
	Header() http.Header
	Payload() any
	ContentType() string
}

// NewHTTPAdapter returns the adapter of svc.
func NewHTTPAdapter(svc ServiceInterface, opts ...ServerOption) *HTTPAdapter {
	o := NewServerOptions(opts...)
	return &HTTPAdapter{svc: svc, opts: o, operations: httpserver.NewChain(o.OperationMiddleware...)}
}

// PostHello handles POST /hello.
func (a *HTTPAdapter) PostHello(w http.ResponseWriter, r *http.Request) {
	a.operations.Serve(w, r, "PostHello", a.servePostHello)
}

func (a *HTTPAdapter) servePostHello(w http.ResponseWriter, r *http.Request) {
	opts := &PostHelloServiceRequestOptions{RawRequest: r}
	query := runtime.ParseQuery(r.URL.RawQuery)
	opts.Query = &PostHelloQuery{}
	if err := runtime.DecodeQuery(query, runtime.Param{Name: "q", Style: runtime.StyleForm, IsExplode: true, IsRequired: false, IsJSON: false}, &opts.Query.Q); err != nil {
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorParse, OperationID: "PostHello", ParamName: "q", ParamLocation: "query", Err: err})
		return
	}
	switch contentType := runtime.ContentType(r.Header); contentType {
	case "application/json":
		body, err := a.opts.Presence.JSON(r.Body, runtime.Prop{})
		if err != nil {
			a.failBody(w, r, "PostHello", err)
			return
		}
		if err = runtime.DecodeJSON(body, &opts.Body, false, a.opts.JSONDecoder); err != nil {
			a.failDecode(w, r, "PostHello", err)
			return
		}
	case "":
	default:
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorDecode, OperationID: "PostHello", Status: http.StatusUnsupportedMediaType, Err: runtime.ContentTypeError(contentType)})
		return
	}
	if err := opts.Validate(); err != nil {
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorValidation, OperationID: "PostHello", Err: err})
		return
	}

	res, err := a.svc.PostHello(r.Context(), opts)
	if err != nil {
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorService, OperationID: "PostHello", Err: err})
		return
	}
	if res == nil {
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorService, OperationID: "PostHello", Err: httpserver.ErrNoResponse})
		return
	}
	a.write(w, r, "PostHello", res)
}

func (a *HTTPAdapter) fail(w http.ResponseWriter, r *http.Request, err *httpserver.HandlerError) {
	// A response that failed to write leaves its media type, which is not the error's.
	w.Header().Del("Content-Type")
	a.opts.ErrorHandler.HandleError(w, r, err.StatusCode(), err)
}

func (a *HTTPAdapter) failDecode(w http.ResponseWriter, r *http.Request, id string, err error) {
	a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorDecode, OperationID: id, Err: err})
}

func (a *HTTPAdapter) failBody(w http.ResponseWriter, r *http.Request, id string, err error) {
	kind := httpserver.ErrorDecode
	if validation.Failed(err) {
		kind = httpserver.ErrorValidation
	}
	a.fail(w, r, &httpserver.HandlerError{Kind: kind, OperationID: id, Err: err})
}

func (a *HTTPAdapter) write(w http.ResponseWriter, r *http.Request, id string, res responseData) {
	if err := httpserver.ValidateResponse(res.Payload()); err != nil {
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorResponse, OperationID: id, Err: err})
		return
	}
	if res.ContentType() != "" {
		w.Header().Set("Content-Type", res.ContentType())
	}
	err := httpserver.Writer{Marshal: a.opts.JSONEncoder}.Write(w, res.StatusCode(), res.Header(), res.Payload())
	switch {
	case errors.Is(err, runtime.ErrContentType):
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorResponse, OperationID: id, Err: err})
	case err != nil:
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorService, OperationID: id, Err: err})
	}
}

// WithRouter registers the routes on r instead of a new router.
func WithRouter(r chi.Router) ServerOption {
	return func(o *ServerOptions) {
		o.Router = r
	}
}

// NewRouter registers every operation on a chi router.
func NewRouter(svc ServiceInterface, opts ...ServerOption) chi.Router {
	o := NewServerOptions(opts...)
	a := NewHTTPAdapter(svc, opts...)
	register := func(r chi.Router) {
		r.Post("/hello", a.PostHello)
	}

	router, _ := o.Router.(chi.Router)
	if router == nil {
		router = chi.NewRouter()
		router.Use(o.Middleware...)
		register(router)
		return router
	}
	router.Group(func(r chi.Router) {
		r.Use(o.Middleware...)
		register(r)
	})
	return router
}
