// Code generated by mockzilla-codegen. DO NOT EDIT.

package hello_world

import (
	"context"

	"github.com/mockzilla/mockzilla/v2/pkg/api"
)

// service implements the ServiceInterface with your business logic.
// Return nil, nil to fall back to the generator for mock responses.
// Return a response to override the generated response.
// Return an error to return an error response.
type service struct {
	params *api.ServiceParams
}

// newService creates a new service instance.
func newService(params *api.ServiceParams) *service {
	return &service{params: params}
}

// PostHello handles POST /hello.
func (s *service) PostHello(ctx context.Context, opts *PostHelloServiceRequestOptions) (*PostHelloResponseData, error) {
	// Return nil, nil to use the generated mock response.
	return nil, nil
}
