// Code generated by mockzilla-codegen. DO NOT EDIT.

package petstore

import (
	"context"
	"encoding/json"
	"errors"
	"net/http"

	chi "github.com/go-chi/chi/v5"
	"github.com/mockzilla/mockzilla-codegen/pkg/runtime"
	"github.com/mockzilla/mockzilla-codegen/pkg/runtime/httpserver"
	"github.com/mockzilla/mockzilla-codegen/pkg/runtime/validation"
)

// Fails to compile when the runtime does not match the generator that wrote this file.
const _ = runtime.SupportsGeneratorV1

type Pet struct {
	Name string  `json:"name"`
	Tag  *string `json:"tag,omitempty"`
	ID   int64   `json:"id"`
}

type NewPet struct {
	Name string  `json:"name"`
	Tag  *string `json:"tag,omitempty"`
}

type Error struct {
	Code    int32  `json:"code"`
	Message string `json:"message"`
}

type FindPetsQuery struct {
	Tags  []string `json:"tags,omitzero"`
	Limit *int32   `json:"limit,omitempty"`
}

type FindPetByIDPathParams struct {
	ID int64 `json:"id"`
}

type DeletePetPathParams struct {
	ID int64 `json:"id"`
}

type FindPetsResponse200 []Pet

// ServiceInterface is what the generated handlers call. Implement it with the business logic.
type ServiceInterface interface {
	// FindPets handles GET /pets.
	FindPets(ctx context.Context, opts *FindPetsServiceRequestOptions) (*FindPetsResponseData, error)
	// AddPet handles POST /pets.
	AddPet(ctx context.Context, opts *AddPetServiceRequestOptions) (*AddPetResponseData, error)
	// FindPetByID handles GET /pets/{id}.
	FindPetByID(ctx context.Context, opts *FindPetByIDServiceRequestOptions) (*FindPetByIDResponseData, error)
	// DeletePet handles DELETE /pets/{id}.
	DeletePet(ctx context.Context, opts *DeletePetServiceRequestOptions) (*DeletePetResponseData, error)
}

// FindPetsServiceRequestOptions is what FindPets receives.
type FindPetsServiceRequestOptions struct {
	Query *FindPetsQuery
	// GenerateResponse makes a mock response that satisfies the spec.
	GenerateResponse func() (*FindPetsResponseData, error)
	RawRequest       *http.Request
}

// Validate checks the parameters and the body against the constraints of the spec.
func (o *FindPetsServiceRequestOptions) Validate() error {
	return nil
}

// FindPetsResponseData is what FindPets returns.
type FindPetsResponseData struct {
	Status  int
	Headers http.Header
	Body    any

	contentType string
}

// NewFindPetsResponseData200 returns the 200 response with its application/json body.
func NewFindPetsResponseData200(body FindPetsResponse200) *FindPetsResponseData {
	return &FindPetsResponseData{Status: 200, Body: body, contentType: "application/json"}
}

// NewFindPetsResponseDataDefault returns the default response with its application/json body.
func NewFindPetsResponseDataDefault(status int, body *Error) *FindPetsResponseData {
	return &FindPetsResponseData{Status: status, Body: body, contentType: "application/json"}
}

// WithStatus sets the status code.
func (r *FindPetsResponseData) WithStatus(code int) *FindPetsResponseData {
	r.Status = code
	return r
}

// WithHeaders sets the headers.
func (r *FindPetsResponseData) WithHeaders(h http.Header) *FindPetsResponseData {
	r.Headers = h
	return r
}

// StatusCode returns the status.
func (r *FindPetsResponseData) StatusCode() int {
	return r.Status
}

// Header returns the headers.
func (r *FindPetsResponseData) Header() http.Header {
	return r.Headers
}

// Payload returns the body.
func (r *FindPetsResponseData) Payload() any {
	return r.Body
}

// ContentType returns the media type of the body, empty for the default of its Go type.
func (r *FindPetsResponseData) ContentType() string {
	return r.contentType
}

// AddPetServiceRequestOptions is what AddPet receives.
type AddPetServiceRequestOptions struct {
	// Body sent as application/json.
	Body *NewPet
	// GenerateResponse makes a mock response that satisfies the spec.
	GenerateResponse func() (*AddPetResponseData, error)
	RawRequest       *http.Request
}

// Validate checks the parameters and the body against the constraints of the spec.
func (o *AddPetServiceRequestOptions) Validate() error {
	return nil
}

// AddPetResponseData is what AddPet returns.
type AddPetResponseData struct {
	Status  int
	Headers http.Header
	Body    any

	contentType string
}

// NewAddPetResponseData200 returns the 200 response with its application/json body.
func NewAddPetResponseData200(body *Pet) *AddPetResponseData {
	return &AddPetResponseData{Status: 200, Body: body, contentType: "application/json"}
}

// NewAddPetResponseDataDefault returns the default response with its application/json body.
func NewAddPetResponseDataDefault(status int, body *Error) *AddPetResponseData {
	return &AddPetResponseData{Status: status, Body: body, contentType: "application/json"}
}

// WithStatus sets the status code.
func (r *AddPetResponseData) WithStatus(code int) *AddPetResponseData {
	r.Status = code
	return r
}

// WithHeaders sets the headers.
func (r *AddPetResponseData) WithHeaders(h http.Header) *AddPetResponseData {
	r.Headers = h
	return r
}

// StatusCode returns the status.
func (r *AddPetResponseData) StatusCode() int {
	return r.Status
}

// Header returns the headers.
func (r *AddPetResponseData) Header() http.Header {
	return r.Headers
}

// Payload returns the body.
func (r *AddPetResponseData) Payload() any {
	return r.Body
}

// ContentType returns the media type of the body, empty for the default of its Go type.
func (r *AddPetResponseData) ContentType() string {
	return r.contentType
}

// FindPetByIDServiceRequestOptions is what FindPetByID receives.
type FindPetByIDServiceRequestOptions struct {
	PathParams *FindPetByIDPathParams
	// GenerateResponse makes a mock response that satisfies the spec.
	GenerateResponse func() (*FindPetByIDResponseData, error)
	RawRequest       *http.Request
}

// Validate checks the parameters and the body against the constraints of the spec.
func (o *FindPetByIDServiceRequestOptions) Validate() error {
	return nil
}

// FindPetByIDResponseData is what FindPetByID returns.
type FindPetByIDResponseData struct {
	Status  int
	Headers http.Header
	Body    any

	contentType string
}

// NewFindPetByIDResponseData200 returns the 200 response with its application/json body.
func NewFindPetByIDResponseData200(body *Pet) *FindPetByIDResponseData {
	return &FindPetByIDResponseData{Status: 200, Body: body, contentType: "application/json"}
}

// NewFindPetByIDResponseDataDefault returns the default response with its application/json body.
func NewFindPetByIDResponseDataDefault(status int, body *Error) *FindPetByIDResponseData {
	return &FindPetByIDResponseData{Status: status, Body: body, contentType: "application/json"}
}

// WithStatus sets the status code.
func (r *FindPetByIDResponseData) WithStatus(code int) *FindPetByIDResponseData {
	r.Status = code
	return r
}

// WithHeaders sets the headers.
func (r *FindPetByIDResponseData) WithHeaders(h http.Header) *FindPetByIDResponseData {
	r.Headers = h
	return r
}

// StatusCode returns the status.
func (r *FindPetByIDResponseData) StatusCode() int {
	return r.Status
}

// Header returns the headers.
func (r *FindPetByIDResponseData) Header() http.Header {
	return r.Headers
}

// Payload returns the body.
func (r *FindPetByIDResponseData) Payload() any {
	return r.Body
}

// ContentType returns the media type of the body, empty for the default of its Go type.
func (r *FindPetByIDResponseData) ContentType() string {
	return r.contentType
}

// DeletePetServiceRequestOptions is what DeletePet receives.
type DeletePetServiceRequestOptions struct {
	PathParams *DeletePetPathParams
	// GenerateResponse makes a mock response that satisfies the spec.
	GenerateResponse func() (*DeletePetResponseData, error)
	RawRequest       *http.Request
}

// Validate checks the parameters and the body against the constraints of the spec.
func (o *DeletePetServiceRequestOptions) Validate() error {
	return nil
}

// DeletePetResponseData is what DeletePet returns.
type DeletePetResponseData struct {
	Status  int
	Headers http.Header
	Body    any

	contentType string
}

// NewDeletePetResponseData204 returns the 204 response.
func NewDeletePetResponseData204() *DeletePetResponseData {
	return &DeletePetResponseData{Status: 204, contentType: ""}
}

// NewDeletePetResponseDataDefault returns the default response with its application/json body.
func NewDeletePetResponseDataDefault(status int, body *Error) *DeletePetResponseData {
	return &DeletePetResponseData{Status: status, Body: body, contentType: "application/json"}
}

// WithStatus sets the status code.
func (r *DeletePetResponseData) WithStatus(code int) *DeletePetResponseData {
	r.Status = code
	return r
}

// WithHeaders sets the headers.
func (r *DeletePetResponseData) WithHeaders(h http.Header) *DeletePetResponseData {
	r.Headers = h
	return r
}

// StatusCode returns the status.
func (r *DeletePetResponseData) StatusCode() int {
	return r.Status
}

// Header returns the headers.
func (r *DeletePetResponseData) Header() http.Header {
	return r.Headers
}

// Payload returns the body.
func (r *DeletePetResponseData) Payload() any {
	return r.Body
}

// ContentType returns the media type of the body, empty for the default of its Go type.
func (r *DeletePetResponseData) ContentType() string {
	return r.contentType
}

// The error types the handlers use, as the runtime declares them.
type (
	ErrorKind           = httpserver.ErrorKind
	HandlerError        = httpserver.HandlerError
	ErrorHandler        = httpserver.ErrorHandler
	ErrorHandlerFunc    = httpserver.ErrorHandlerFunc
	DefaultErrorHandler = httpserver.DefaultErrorHandler
)

// The kinds of HandlerError.
const (
	ErrorParse      = httpserver.ErrorParse
	ErrorDecode     = httpserver.ErrorDecode
	ErrorValidation = httpserver.ErrorValidation
	ErrorService    = httpserver.ErrorService
	ErrorResponse   = httpserver.ErrorResponse
)

var bodyPresence = runtime.Presence{
	IsChecked: true,
	Objects: []runtime.Object{
		{Name: "NewPet", Props: []runtime.Prop{
			{Key: "name", IsRequired: true},
			{Key: "tag"},
		}},
	},
}

// ServerOptions is what the adapter and the router are set up with.
type ServerOptions struct {
	Router              any
	Middleware          []func(http.Handler) http.Handler
	OperationMiddleware []func(http.Handler) http.Handler
	ErrorHandler        httpserver.ErrorHandler
	JSONDecoder         func(data []byte, v any) error
	JSONEncoder         func(v any) ([]byte, error)
	MultipartMaxMemory  int64
	Presence            runtime.PresenceChecker
}

// ServerOption sets one field of ServerOptions.
type ServerOption func(*ServerOptions)

// NewServerOptions applies opts to the defaults.
func NewServerOptions(opts ...ServerOption) *ServerOptions {
	o := &ServerOptions{
		ErrorHandler:       httpserver.DefaultErrorHandler{},
		JSONDecoder:        json.Unmarshal,
		JSONEncoder:        json.Marshal,
		MultipartMaxMemory: 33554432,
		Presence:           bodyPresence,
	}
	for _, opt := range opts {
		opt(o)
	}
	return o
}

// WithMiddleware wraps the routes with mw, outermost first; on a new router, unknown paths too.
func WithMiddleware(mw ...func(http.Handler) http.Handler) ServerOption {
	return func(o *ServerOptions) {
		o.Middleware = append(o.Middleware, mw...)
	}
}

// WithOperationMiddleware wraps each operation with mw, once its name is on the context.
func WithOperationMiddleware(mw ...func(http.Handler) http.Handler) ServerOption {
	return func(o *ServerOptions) {
		o.OperationMiddleware = append(o.OperationMiddleware, mw...)
	}
}

// WithErrorHandler sets what writes the response of a failed request.
func WithErrorHandler(h httpserver.ErrorHandler) ServerOption {
	return func(o *ServerOptions) {
		o.ErrorHandler = h
	}
}

// WithJSONDecoder sets what reads JSON request bodies.
func WithJSONDecoder(decode func(data []byte, v any) error) ServerOption {
	return func(o *ServerOptions) {
		o.JSONDecoder = decode
	}
}

// WithJSONEncoder sets what writes JSON response bodies and stream frames.
func WithJSONEncoder(encode func(v any) ([]byte, error)) ServerOption {
	return func(o *ServerOptions) {
		o.JSONEncoder = encode
	}
}

// WithMultipartMaxMemory sets how much of a multipart form stays in memory.
func WithMultipartMaxMemory(n int64) ServerOption {
	return func(o *ServerOptions) {
		o.MultipartMaxMemory = n
	}
}

// WithPresence sets what checks the keys of request bodies and fills their defaults.
func WithPresence(p runtime.PresenceChecker) ServerOption {
	return func(o *ServerOptions) {
		o.Presence = p
	}
}

// HTTPAdapter answers HTTP requests by calling the service.
type HTTPAdapter struct {
	svc        ServiceInterface
	opts       *ServerOptions
	operations httpserver.Chain
}

type responseData interface {
	StatusCode() int
	Header() http.Header
	Payload() any
	ContentType() string
}

// NewHTTPAdapter returns the adapter of svc.
func NewHTTPAdapter(svc ServiceInterface, opts ...ServerOption) *HTTPAdapter {
	o := NewServerOptions(opts...)
	return &HTTPAdapter{svc: svc, opts: o, operations: httpserver.NewChain(o.OperationMiddleware...)}
}

// FindPets handles GET /pets.
func (a *HTTPAdapter) FindPets(w http.ResponseWriter, r *http.Request) {
	a.operations.Serve(w, r, "FindPets", a.serveFindPets)
}

func (a *HTTPAdapter) serveFindPets(w http.ResponseWriter, r *http.Request) {
	opts := &FindPetsServiceRequestOptions{RawRequest: r}
	query := runtime.ParseQuery(r.URL.RawQuery)
	opts.Query = &FindPetsQuery{}
	if err := runtime.DecodeQuery(query, runtime.Param{Name: "tags", Style: runtime.StyleForm, IsExplode: true, IsRequired: false, IsJSON: false}, &opts.Query.Tags); err != nil {
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorParse, OperationID: "FindPets", ParamName: "tags", ParamLocation: "query", Err: err})
		return
	}
	if err := runtime.DecodeQuery(query, runtime.Param{Name: "limit", Style: runtime.StyleForm, IsExplode: true, IsRequired: false, IsJSON: false}, &opts.Query.Limit); err != nil {
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorParse, OperationID: "FindPets", ParamName: "limit", ParamLocation: "query", Err: err})
		return
	}
	if err := opts.Validate(); err != nil {
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorValidation, OperationID: "FindPets", Err: err})
		return
	}

	res, err := a.svc.FindPets(r.Context(), opts)
	if err != nil {
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorService, OperationID: "FindPets", Err: err})
		return
	}
	if res == nil {
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorService, OperationID: "FindPets", Err: httpserver.ErrNoResponse})
		return
	}
	a.write(w, r, "FindPets", res)
}

// AddPet handles POST /pets.
func (a *HTTPAdapter) AddPet(w http.ResponseWriter, r *http.Request) {
	a.operations.Serve(w, r, "AddPet", a.serveAddPet)
}

func (a *HTTPAdapter) serveAddPet(w http.ResponseWriter, r *http.Request) {
	opts := &AddPetServiceRequestOptions{RawRequest: r}
	switch contentType := runtime.ContentType(r.Header); contentType {
	case "application/json":
		body, err := a.opts.Presence.JSON(r.Body, runtime.Prop{Object: "NewPet"})
		if err != nil {
			a.failBody(w, r, "AddPet", err)
			return
		}
		if err = runtime.DecodeJSON(body, &opts.Body, true, a.opts.JSONDecoder); err != nil {
			a.failDecode(w, r, "AddPet", err)
			return
		}
	case "":
		a.failDecode(w, r, "AddPet", runtime.ErrBodyEmpty)
		return
	default:
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorDecode, OperationID: "AddPet", Status: http.StatusUnsupportedMediaType, Err: runtime.ContentTypeError(contentType)})
		return
	}
	if err := opts.Validate(); err != nil {
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorValidation, OperationID: "AddPet", Err: err})
		return
	}

	res, err := a.svc.AddPet(r.Context(), opts)
	if err != nil {
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorService, OperationID: "AddPet", Err: err})
		return
	}
	if res == nil {
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorService, OperationID: "AddPet", Err: httpserver.ErrNoResponse})
		return
	}
	a.write(w, r, "AddPet", res)
}

// FindPetByID handles GET /pets/{id}.
func (a *HTTPAdapter) FindPetByID(w http.ResponseWriter, r *http.Request) {
	a.operations.Serve(w, r, "FindPetByID", a.serveFindPetByID)
}

func (a *HTTPAdapter) serveFindPetByID(w http.ResponseWriter, r *http.Request) {
	opts := &FindPetByIDServiceRequestOptions{RawRequest: r}
	opts.PathParams = &FindPetByIDPathParams{}
	if err := runtime.DecodePath(runtime.UnescapePath(r, chi.URLParam(r, "id")), runtime.Param{Name: "id", Style: runtime.StyleSimple, IsExplode: false, IsRequired: true, IsJSON: false}, &opts.PathParams.ID); err != nil {
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorParse, OperationID: "FindPetByID", ParamName: "id", ParamLocation: "path", Err: err})
		return
	}
	if err := opts.Validate(); err != nil {
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorValidation, OperationID: "FindPetByID", Err: err})
		return
	}

	res, err := a.svc.FindPetByID(r.Context(), opts)
	if err != nil {
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorService, OperationID: "FindPetByID", Err: err})
		return
	}
	if res == nil {
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorService, OperationID: "FindPetByID", Err: httpserver.ErrNoResponse})
		return
	}
	a.write(w, r, "FindPetByID", res)
}

// DeletePet handles DELETE /pets/{id}.
func (a *HTTPAdapter) DeletePet(w http.ResponseWriter, r *http.Request) {
	a.operations.Serve(w, r, "DeletePet", a.serveDeletePet)
}

func (a *HTTPAdapter) serveDeletePet(w http.ResponseWriter, r *http.Request) {
	opts := &DeletePetServiceRequestOptions{RawRequest: r}
	opts.PathParams = &DeletePetPathParams{}
	if err := runtime.DecodePath(runtime.UnescapePath(r, chi.URLParam(r, "id")), runtime.Param{Name: "id", Style: runtime.StyleSimple, IsExplode: false, IsRequired: true, IsJSON: false}, &opts.PathParams.ID); err != nil {
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorParse, OperationID: "DeletePet", ParamName: "id", ParamLocation: "path", Err: err})
		return
	}
	if err := opts.Validate(); err != nil {
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorValidation, OperationID: "DeletePet", Err: err})
		return
	}

	res, err := a.svc.DeletePet(r.Context(), opts)
	if err != nil {
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorService, OperationID: "DeletePet", Err: err})
		return
	}
	if res == nil {
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorService, OperationID: "DeletePet", Err: httpserver.ErrNoResponse})
		return
	}
	a.write(w, r, "DeletePet", res)
}

func (a *HTTPAdapter) fail(w http.ResponseWriter, r *http.Request, err *httpserver.HandlerError) {
	// A response that failed to write leaves its media type, which is not the error's.
	w.Header().Del("Content-Type")
	a.opts.ErrorHandler.HandleError(w, r, err.StatusCode(), err)
}

func (a *HTTPAdapter) failDecode(w http.ResponseWriter, r *http.Request, id string, err error) {
	a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorDecode, OperationID: id, Err: err})
}

func (a *HTTPAdapter) failBody(w http.ResponseWriter, r *http.Request, id string, err error) {
	kind := httpserver.ErrorDecode
	if validation.Failed(err) {
		kind = httpserver.ErrorValidation
	}
	a.fail(w, r, &httpserver.HandlerError{Kind: kind, OperationID: id, Err: err})
}

func (a *HTTPAdapter) write(w http.ResponseWriter, r *http.Request, id string, res responseData) {
	if err := httpserver.ValidateResponse(res.Payload()); err != nil {
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorResponse, OperationID: id, Err: err})
		return
	}
	if res.ContentType() != "" {
		w.Header().Set("Content-Type", res.ContentType())
	}
	err := httpserver.Writer{Marshal: a.opts.JSONEncoder}.Write(w, res.StatusCode(), res.Header(), res.Payload())
	switch {
	case errors.Is(err, runtime.ErrContentType):
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorResponse, OperationID: id, Err: err})
	case err != nil:
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorService, OperationID: id, Err: err})
	}
}

// WithRouter registers the routes on r instead of a new router.
func WithRouter(r chi.Router) ServerOption {
	return func(o *ServerOptions) {
		o.Router = r
	}
}

// NewRouter registers every operation on a chi router.
func NewRouter(svc ServiceInterface, opts ...ServerOption) chi.Router {
	o := NewServerOptions(opts...)
	a := NewHTTPAdapter(svc, opts...)
	register := func(r chi.Router) {
		r.Get("/pets", a.FindPets)
		r.Post("/pets", a.AddPet)
		r.Get("/pets/{id}", a.FindPetByID)
		r.Delete("/pets/{id}", a.DeletePet)
	}

	router, _ := o.Router.(chi.Router)
	if router == nil {
		router = chi.NewRouter()
		router.Use(o.Middleware...)
		register(router)
		return router
	}
	router.Group(func(r chi.Router) {
		r.Use(o.Middleware...)
		register(r)
	})
	return router
}
