// Code generated by oapi-codegen. DO NOT EDIT.

package petstore

import (
	"context"
	"embed"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"log/slog"
	"net/http"
	"path"

	"sync"

	oapicodegen "github.com/doordash-oss/oapi-codegen-dd/v3/pkg/codegen"
	"github.com/doordash-oss/oapi-codegen-dd/v3/pkg/runtime"
	"github.com/go-chi/chi/v5"
	"github.com/go-playground/validator/v10"
	"github.com/mockzilla/mockzilla/v2/pkg/api"
	"github.com/mockzilla/mockzilla/v2/pkg/config"
	"github.com/mockzilla/mockzilla/v2/pkg/db"
	"github.com/mockzilla/mockzilla/v2/pkg/factory"
	"github.com/mockzilla/mockzilla/v2/pkg/generator"
	"github.com/mockzilla/mockzilla/v2/pkg/loader"
	"github.com/mockzilla/mockzilla/v2/pkg/schema"
	"github.com/mockzilla/mockzilla/v2/pkg/typedef"
	yamlv4 "go.yaml.in/yaml/v4"
)

// OapiErrorKind represents the type of error that occurred during request processing.
type OapiErrorKind int

const (
	// OapiErrorKindParse indicates a parameter parsing error (invalid path/query/header parameter).
	OapiErrorKindParse OapiErrorKind = iota

	// OapiErrorKindDecode indicates a request body decoding error (invalid JSON, form data, etc.).
	OapiErrorKindDecode

	// OapiErrorKindValidation indicates a request validation error (failed schema validation).
	OapiErrorKindValidation

	// OapiErrorKindService indicates a service/business logic error returned by the service implementation.
	OapiErrorKindService
)

// OapiHandlerError represents an error that occurred during request handling (parse, decode, validation).
// When no typed error response is configured in the OpenAPI spec, this error type is used.
// Custom error handlers can type-assert to this type to access error details.
type OapiHandlerError struct {
	Kind          OapiErrorKind
	OperationID   string
	Message       string
	ParamName     string
	ParamLocation string
}

func (e OapiHandlerError) Error() string {
	return e.Message
}

// OapiErrorResponse is the default JSON error response structure used by OapiDefaultErrorHandler.
type OapiErrorResponse struct {
	Error         string `json:"error"`
	OperationID   string `json:"operation_id,omitempty"`
	ParamName     string `json:"param_name,omitempty"`
	ParamLocation string `json:"param_location,omitempty"`
}

// OapiErrorHandler handles errors that occur during request processing.
// Implement this interface to customize error responses, logging, and metrics.
type OapiErrorHandler interface {
	// HandleError writes an error response to w with the given status code.
	// The err is either an OapiHandlerError (for parse/decode/validation errors)
	// or a typed error matching the OpenAPI spec's error response schema.
	HandleError(w http.ResponseWriter, r *http.Request, statusCode int, err error)
}

// OapiDefaultErrorHandler provides the default error handling behavior.
// It writes JSON error responses. For OapiHandlerError, it uses OapiErrorResponse.
// For typed errors (from OpenAPI spec), it encodes them directly.
type OapiDefaultErrorHandler struct{}

// HandleError implements OapiErrorHandler with default JSON error responses.
func (h *OapiDefaultErrorHandler) HandleError(w http.ResponseWriter, r *http.Request, statusCode int, err error) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(statusCode)

	if handlerErr, ok := err.(OapiHandlerError); ok {
		_ = json.NewEncoder(w).Encode(OapiErrorResponse{
			Error:         handlerErr.Message,
			OperationID:   handlerErr.OperationID,
			ParamName:     handlerErr.ParamName,
			ParamLocation: handlerErr.ParamLocation,
		})
		return
	}

	// Typed error from OpenAPI spec - encode directly
	_ = json.NewEncoder(w).Encode(err)
}

// ServiceInterface defines the service interface for business logic.
type ServiceInterface interface {
	FindPets(ctx context.Context, opts *FindPetsServiceRequestOptions) (*FindPetsResponseData, error)

	AddPet(ctx context.Context, opts *AddPetServiceRequestOptions) (*AddPetResponseData, error)

	FindPetByID(ctx context.Context, opts *FindPetByIDServiceRequestOptions) (*FindPetByIDResponseData, error)

	DeletePet(ctx context.Context, opts *DeletePetServiceRequestOptions) (*DeletePetResponseData, error)
}

// HTTPAdapter adapts the ServiceInterface to HTTP handlers.
// This struct is generated and should not be modified.
type HTTPAdapter struct {
	svc             ServiceInterface
	errHandler      OapiErrorHandler
	jsonBodyDecoder runtime.JSONBodyDecoderFunc
}

// NewHTTPAdapter creates a new HTTPAdapter wrapping the given service.
// If errHandler is nil, OapiDefaultErrorHandler is used.
func NewHTTPAdapter(svc ServiceInterface, errHandler OapiErrorHandler) *HTTPAdapter {
	if errHandler == nil {
		errHandler = &OapiDefaultErrorHandler{}
	}
	return &HTTPAdapter{svc: svc, errHandler: errHandler, jsonBodyDecoder: runtime.DecodeJSONBody}
}

// FindPets handles GET /pets
func (a *HTTPAdapter) FindPets(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()
	opts := &FindPetsServiceRequestOptions{}
	opts.RawRequest = r

	// Parse query parameters
	queryParams := &FindPetsQuery{}
	query := r.URL.Query()

	if values, ok := query["tags"]; ok {
		queryParams.Tags = values
	}
	if queryParamLimitStr := query.Get("limit"); queryParamLimitStr != "" {
		queryParamLimit, err := runtime.ParseString[int32](queryParamLimitStr, "int32")
		if err != nil {
			a.errHandler.HandleError(w, r, http.StatusBadRequest, OapiHandlerError{
				Kind:          OapiErrorKindParse,
				OperationID:   "FindPets",
				Message:       err.Error(),
				ParamName:     "limit",
				ParamLocation: "query",
			})
			return
		}
		queryParams.Limit = &queryParamLimit
	}
	opts.Query = queryParams
	// Validate request
	if err := opts.Validate(); err != nil {
		a.errHandler.HandleError(w, r, http.StatusBadRequest, OapiHandlerError{
			Kind:        OapiErrorKindValidation,
			OperationID: "FindPets",
			Message:     err.Error(),
		})
		return
	}

	// Call business logic
	resp, err := a.svc.FindPets(ctx, opts)
	if err != nil {
		code := http.StatusInternalServerError
		if resp != nil && resp.Status != 0 {
			code = resp.Status
		}
		a.errHandler.HandleError(w, r, code, err)
		return
	}

	// Validate response
	if resp != nil && resp.Body != nil {
		if v, ok := any(resp.Body).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				a.errHandler.HandleError(w, r, http.StatusInternalServerError, OapiHandlerError{
					Kind:        OapiErrorKindValidation,
					OperationID: "FindPets",
					Message:     fmt.Sprintf("response validation failed: %v", err),
				})
				return
			}
		}
	}

	// Apply custom headers from response
	if resp != nil && resp.Headers != nil {
		for k, v := range resp.Headers {
			for _, val := range v {
				w.Header().Add(k, val)
			}
		}
	}

	// Determine status code
	status := 200
	if resp != nil && resp.Status != 0 {
		status = resp.Status
	}
	if w.Header().Get("Content-Type") == "" {
		w.Header().Set("Content-Type", "application/json")
	}
	w.WriteHeader(status)
	if resp != nil && resp.Body != nil {
		_ = json.NewEncoder(w).Encode(resp.Body)
	}
}

// AddPet handles POST /pets
func (a *HTTPAdapter) AddPet(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()
	opts := &AddPetServiceRequestOptions{}
	opts.RawRequest = r

	// Parse request body
	defer r.Body.Close()
	var body AddPetBody
	if err := a.jsonBodyDecoder(r.Body, &body); err != nil {
		a.errHandler.HandleError(w, r, http.StatusBadRequest, OapiHandlerError{
			Kind:        OapiErrorKindDecode,
			OperationID: "AddPet",
			Message:     err.Error(),
		})
		return
	}
	opts.Body = &body
	// Validate request
	if err := opts.Validate(); err != nil {
		a.errHandler.HandleError(w, r, http.StatusBadRequest, OapiHandlerError{
			Kind:        OapiErrorKindValidation,
			OperationID: "AddPet",
			Message:     err.Error(),
		})
		return
	}

	// Call business logic
	resp, err := a.svc.AddPet(ctx, opts)
	if err != nil {
		code := http.StatusInternalServerError
		if resp != nil && resp.Status != 0 {
			code = resp.Status
		}
		a.errHandler.HandleError(w, r, code, err)
		return
	}

	// Validate response
	if resp != nil && resp.Body != nil {
		if v, ok := any(resp.Body).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				a.errHandler.HandleError(w, r, http.StatusInternalServerError, OapiHandlerError{
					Kind:        OapiErrorKindValidation,
					OperationID: "AddPet",
					Message:     fmt.Sprintf("response validation failed: %v", err),
				})
				return
			}
		}
	}

	// Apply custom headers from response
	if resp != nil && resp.Headers != nil {
		for k, v := range resp.Headers {
			for _, val := range v {
				w.Header().Add(k, val)
			}
		}
	}

	// Determine status code
	status := 200
	if resp != nil && resp.Status != 0 {
		status = resp.Status
	}
	if w.Header().Get("Content-Type") == "" {
		w.Header().Set("Content-Type", "application/json")
	}
	w.WriteHeader(status)
	if resp != nil && resp.Body != nil {
		_ = json.NewEncoder(w).Encode(resp.Body)
	}
}

// FindPetByID handles GET /pets/{id}
func (a *HTTPAdapter) FindPetByID(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()
	opts := &FindPetByIDServiceRequestOptions{}
	opts.RawRequest = r

	// Parse path parameters
	pathParams := &FindPetByIDPath{}
	pathParamIDStr := chi.URLParam(r, "id")

	pathParamID, err := runtime.ParseString[int64](pathParamIDStr, "int64")
	if err != nil {
		a.errHandler.HandleError(w, r, http.StatusBadRequest, OapiHandlerError{
			Kind:          OapiErrorKindParse,
			OperationID:   "FindPetByID",
			Message:       err.Error(),
			ParamName:     "id",
			ParamLocation: "path",
		})
		return
	}
	pathParams.ID = pathParamID
	opts.PathParams = pathParams
	// Validate request
	if err := opts.Validate(); err != nil {
		a.errHandler.HandleError(w, r, http.StatusBadRequest, OapiHandlerError{
			Kind:        OapiErrorKindValidation,
			OperationID: "FindPetByID",
			Message:     err.Error(),
		})
		return
	}

	// Call business logic
	resp, err := a.svc.FindPetByID(ctx, opts)
	if err != nil {
		code := http.StatusInternalServerError
		if resp != nil && resp.Status != 0 {
			code = resp.Status
		}
		a.errHandler.HandleError(w, r, code, err)
		return
	}

	// Validate response
	if resp != nil && resp.Body != nil {
		if v, ok := any(resp.Body).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				a.errHandler.HandleError(w, r, http.StatusInternalServerError, OapiHandlerError{
					Kind:        OapiErrorKindValidation,
					OperationID: "FindPetByID",
					Message:     fmt.Sprintf("response validation failed: %v", err),
				})
				return
			}
		}
	}

	// Apply custom headers from response
	if resp != nil && resp.Headers != nil {
		for k, v := range resp.Headers {
			for _, val := range v {
				w.Header().Add(k, val)
			}
		}
	}

	// Determine status code
	status := 200
	if resp != nil && resp.Status != 0 {
		status = resp.Status
	}
	if w.Header().Get("Content-Type") == "" {
		w.Header().Set("Content-Type", "application/json")
	}
	w.WriteHeader(status)
	if resp != nil && resp.Body != nil {
		_ = json.NewEncoder(w).Encode(resp.Body)
	}
}

// DeletePet handles DELETE /pets/{id}
func (a *HTTPAdapter) DeletePet(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()
	opts := &DeletePetServiceRequestOptions{}
	opts.RawRequest = r

	// Parse path parameters
	pathParams := &DeletePetPath{}
	pathParamIDStr := chi.URLParam(r, "id")

	pathParamID, err := runtime.ParseString[int64](pathParamIDStr, "int64")
	if err != nil {
		a.errHandler.HandleError(w, r, http.StatusBadRequest, OapiHandlerError{
			Kind:          OapiErrorKindParse,
			OperationID:   "DeletePet",
			Message:       err.Error(),
			ParamName:     "id",
			ParamLocation: "path",
		})
		return
	}
	pathParams.ID = pathParamID
	opts.PathParams = pathParams
	// Validate request
	if err := opts.Validate(); err != nil {
		a.errHandler.HandleError(w, r, http.StatusBadRequest, OapiHandlerError{
			Kind:        OapiErrorKindValidation,
			OperationID: "DeletePet",
			Message:     err.Error(),
		})
		return
	}

	// Call business logic
	resp, err := a.svc.DeletePet(ctx, opts)
	if err != nil {
		code := http.StatusInternalServerError
		if resp != nil && resp.Status != 0 {
			code = resp.Status
		}
		a.errHandler.HandleError(w, r, code, err)
		return
	}

	// Validate response
	if resp != nil && resp.Body != nil {
		if v, ok := any(resp.Body).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				a.errHandler.HandleError(w, r, http.StatusInternalServerError, OapiHandlerError{
					Kind:        OapiErrorKindValidation,
					OperationID: "DeletePet",
					Message:     fmt.Sprintf("response validation failed: %v", err),
				})
				return
			}
		}
	}

	// Apply custom headers from response
	if resp != nil && resp.Headers != nil {
		for k, v := range resp.Headers {
			for _, val := range v {
				w.Header().Add(k, val)
			}
		}
	}

	// Determine status code
	status := 204
	if resp != nil && resp.Status != 0 {
		status = resp.Status
	}
	w.WriteHeader(status)
}

// RouterOption is a function that configures the router.
type RouterOption func(*routerConfig)

type routerConfig struct {
	middlewares []func(http.Handler) http.Handler
	errHandler  OapiErrorHandler
}

// WithMiddleware adds middleware to the router.
func WithMiddleware(mw func(http.Handler) http.Handler) RouterOption {
	return func(cfg *routerConfig) {
		cfg.middlewares = append(cfg.middlewares, mw)
	}
}

// WithErrorHandler sets a custom error handler for the router.
// If not set, OapiOapiDefaultErrorHandler is used.
func WithErrorHandler(h OapiErrorHandler) RouterOption {
	return func(cfg *routerConfig) {
		cfg.errHandler = h
	}
}

// NewRouter creates a new chi.Router with the given service implementation.
func NewRouter(svc ServiceInterface, opts ...RouterOption) chi.Router {
	cfg := &routerConfig{}
	for _, opt := range opts {
		opt(cfg)
	}

	r := chi.NewRouter()
	r.Use(api.ContextReplacementsMiddleware)
	for _, mw := range cfg.middlewares {
		r.Use(mw)
	}
	adapter := NewHTTPAdapter(svc, cfg.errHandler)
	r.Method("GET", "/pets", http.HandlerFunc(adapter.FindPets))
	r.Method("POST", "/pets", http.HandlerFunc(adapter.AddPet))
	r.Method("GET", "/pets/{id}", http.HandlerFunc(adapter.FindPetByID))
	r.Method("DELETE", "/pets/{id}", http.HandlerFunc(adapter.DeletePet))

	return r
}

// ============================================================================
// mockzilla Service Registration
// ============================================================================

//go:embed setup/config.yml
var configSrc []byte

//go:embed setup/openapi.*
var openapiSpecFS embed.FS

//go:embed setup/codegen.yml
var codegenConfigSrc []byte

//go:embed setup/context.yml
var contextSrc []byte

var cfg *config.ServiceConfig

func init() {
	var err error
	cfg, err = config.NewServiceConfigFromBytes(configSrc)
	if err != nil {
		slog.Error("Failed to parse service config", "error", err)
		return
	}
	loader.Register(cfg.Name, RegisterAPIRouter)
}

// Register registers the service with the central router.
func RegisterAPIRouter(router *api.Router) {
	serviceName := cfg.Name

	// Read OpenAPI spec from embedded FS
	openapiSpec, err := readFirstEmbeddedFile(openapiSpecFS)
	if err != nil {
		slog.Error(fmt.Sprintf("Failed to read OpenAPI spec for %s", serviceName),
			"error", err,
			"service", serviceName,
		)
		return
	}

	// Load codegen config
	var codegenCfg oapicodegen.Configuration
	if err := yamlv4.Unmarshal(codegenConfigSrc, &codegenCfg); err != nil {
		slog.Error(fmt.Sprintf("Failed to parse codegen config for %s", serviceName),
			"error", err,
			"service", serviceName,
		)
		return
	}
	codegenCfg = codegenCfg.Merge(oapicodegen.NewDefaultConfiguration())

	// Create the typedef registry from the OpenAPI spec
	registry, err := typedef.NewRegistryFromSpec(openapiSpec, codegenCfg, cfg.SpecOptions)
	if err != nil {
		slog.Error(fmt.Sprintf("Failed to create registry for %s", serviceName),
			"error", err,
			"service", serviceName,
		)
		return
	}

	// Create the generator with service contexts
	orderedCtx := generator.LoadServiceContext(contextSrc, router.GetContexts())
	gen, err := generator.NewGenerator(orderedCtx, router.GetContexts())
	if err != nil {
		slog.Error(fmt.Sprintf("Failed to create generator for %s", serviceName),
			"error", err,
			"service", serviceName,
		)
		return
	}

	// Register with mockzilla using handler factory
	router.RegisterHTTPHandler(cfg, func(serviceDB db.DB) api.Handler {
		userSvc := newService(&api.ServiceParams{
			AppConfig:     router.Config(),
			ServiceConfig: cfg,
			DB:            serviceDB,
		})
		genSvc := &generatorService{service: userSvc, generator: gen, registry: registry}
		return newServiceHandler(genSvc, gen, registry)
	})

	slog.Info(fmt.Sprintf("Registered %s service", serviceName),
		"service", serviceName,
	)
}

// readFirstEmbeddedFile reads the first file from an embedded filesystem.
func readFirstEmbeddedFile(fsys embed.FS) ([]byte, error) {
	entries, err := fsys.ReadDir("setup")
	if err != nil {
		return nil, fmt.Errorf("reading embedded directory: %w", err)
	}
	for _, entry := range entries {
		if !entry.IsDir() {
			return fsys.ReadFile(path.Join("setup", entry.Name()))
		}
	}
	return nil, errors.New("no file found in embedded filesystem")
}

// ============================================================================
// Service Handler
// ============================================================================

// serviceHandler wraps the chi router and service to implement api.Handler.
type serviceHandler struct {
	router   chi.Router
	service  ServiceInterface
	gen      generator.Generate
	registry typedef.OperationRegistry
}

// newServiceHandler creates a new serviceHandler.
func newServiceHandler(svc ServiceInterface, gen generator.Generate, registry typedef.OperationRegistry) api.Handler {
	return &serviceHandler{
		router:   NewRouter(svc),
		service:  svc,
		gen:      gen,
		registry: registry,
	}
}

func (h *serviceHandler) Routes() api.RouteDescriptions {
	routes := h.router.Routes()
	descriptions := make(api.RouteDescriptions, 0, len(routes))
	for _, route := range routes {
		for method := range route.Handlers {
			descriptions = append(descriptions, &api.RouteDescription{
				Method: method,
				Path:   route.Pattern,
			})
		}
	}
	return descriptions
}

func (h *serviceHandler) RegisterRoutes(router chi.Router) {
	router.Mount("/", h.router)
}

func (h *serviceHandler) Generate(w http.ResponseWriter, r *http.Request) {
	var req api.GenerateRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		message := err.Error()
		if errors.Is(err, io.EOF) {
			message = "request body is empty or incomplete"
		}
		slog.Error("Failed to decode request", "error", err)
		http.Error(w, message, http.StatusBadRequest)
		return
	}

	op := h.registry.FindOperation(req.Path, req.Method)
	res := h.gen.Request(&req, op, req.Context)
	api.NewJSONResponse(w).Send(res)
}

// ============================================================================
// Generator Service (fallback to mock responses)
// ============================================================================

// generatorService implements ServiceInterface with generator fallback.
// It delegates to the user's service first; if that returns nil, it generates a mock response.
type generatorService struct {
	service   *service
	generator generator.Generate
	registry  typedef.OperationRegistry
}

// Ensure generatorService implements ServiceInterface.
var _ ServiceInterface = (*generatorService)(nil)

// FindPets handles GET /pets
func (s *generatorService) FindPets(ctx context.Context, opts *FindPetsServiceRequestOptions) (*FindPetsResponseData, error) {
	// Inject GenerateResponse so user service can call it
	opts.GenerateResponse = func() (*FindPetsResponseData, error) {
		respSchema := s.registry.GetResponseSchema("/pets", "GET")
		if respSchema == nil {
			return NewFindPetsResponseData(nil), nil
		}
		res := s.generator.Response(respSchema, api.UserContextFromGoContext(ctx))
		var body FindPetsResponse
		if err := api.UnmarshalResponseInto(res.Body, "application/json", &body); err != nil {
			return nil, err
		}
		return NewFindPetsResponseData(&body).WithHeaders(res.Headers), nil
	}

	// Call user's service
	if resp, err := s.service.FindPets(ctx, opts); resp != nil || err != nil {
		return resp, err
	}

	// Fallback to generator
	return opts.GenerateResponse()
}

// AddPet handles POST /pets
func (s *generatorService) AddPet(ctx context.Context, opts *AddPetServiceRequestOptions) (*AddPetResponseData, error) {
	// Inject GenerateResponse so user service can call it
	opts.GenerateResponse = func() (*AddPetResponseData, error) {
		respSchema := s.registry.GetResponseSchema("/pets", "POST")
		if respSchema == nil {
			return NewAddPetResponseData(nil), nil
		}
		res := s.generator.Response(respSchema, api.UserContextFromGoContext(ctx))
		var body AddPetResponse
		if err := api.UnmarshalResponseInto(res.Body, "application/json", &body); err != nil {
			return nil, err
		}
		return NewAddPetResponseData(&body).WithHeaders(res.Headers), nil
	}

	// Call user's service
	if resp, err := s.service.AddPet(ctx, opts); resp != nil || err != nil {
		return resp, err
	}

	// Fallback to generator
	return opts.GenerateResponse()
}

// FindPetByID handles GET /pets/{id}
func (s *generatorService) FindPetByID(ctx context.Context, opts *FindPetByIDServiceRequestOptions) (*FindPetByIDResponseData, error) {
	// Inject GenerateResponse so user service can call it
	opts.GenerateResponse = func() (*FindPetByIDResponseData, error) {
		respSchema := s.registry.GetResponseSchema("/pets/{id}", "GET")
		if respSchema == nil {
			return NewFindPetByIDResponseData(nil), nil
		}
		res := s.generator.Response(respSchema, api.UserContextFromGoContext(ctx))
		var body FindPetByIDResponse
		if err := api.UnmarshalResponseInto(res.Body, "application/json", &body); err != nil {
			return nil, err
		}
		return NewFindPetByIDResponseData(&body).WithHeaders(res.Headers), nil
	}

	// Call user's service
	if resp, err := s.service.FindPetByID(ctx, opts); resp != nil || err != nil {
		return resp, err
	}

	// Fallback to generator
	return opts.GenerateResponse()
}

// DeletePet handles DELETE /pets/{id}
func (s *generatorService) DeletePet(ctx context.Context, opts *DeletePetServiceRequestOptions) (*DeletePetResponseData, error) {
	// Inject GenerateResponse so user service can call it
	opts.GenerateResponse = func() (*DeletePetResponseData, error) {
		respSchema := s.registry.GetResponseSchema("/pets/{id}", "DELETE")
		if respSchema == nil {
			return NewDeletePetResponseData(nil), nil
		}
		res := s.generator.Response(respSchema, api.UserContextFromGoContext(ctx))
		return NewDeletePetResponseData(nil).WithHeaders(res.Headers), nil
	}

	// Call user's service
	if resp, err := s.service.DeletePet(ctx, opts); resp != nil || err != nil {
		return resp, err
	}

	// Fallback to generator
	return opts.GenerateResponse()
}

// ============================================================================
// Factory (programmatic request/response generation)
// ============================================================================

var (
	defaultFactory     *factory.Factory
	defaultFactoryOnce sync.Once
	defaultFactoryErr  error
)

// NewFactory creates a Factory pre-configured with this service's OpenAPI spec,
// codegen config, spec options, and context.
// Use it to generate mock requests and responses programmatically without running the server.
func NewFactory(opts ...factory.FactoryOption) (*factory.Factory, error) {
	openapiSpec, err := readFirstEmbeddedFile(openapiSpecFS)
	if err != nil {
		return nil, err
	}

	var codegenCfg oapicodegen.Configuration
	if err := yamlv4.Unmarshal(codegenConfigSrc, &codegenCfg); err != nil {
		return nil, err
	}

	allOpts := []factory.FactoryOption{
		factory.WithServiceContext(contextSrc),
		factory.WithCodegenConfig(codegenCfg),
	}
	if cfg != nil && cfg.SpecOptions != nil {
		allOpts = append(allOpts, factory.WithSpecOptions(cfg.SpecOptions))
	}
	allOpts = append(allOpts, opts...)
	return factory.NewFactory(openapiSpec, allOpts...)
}

// GetFactory returns a singleton Factory instance.
// The factory is initialized on first call and reused for subsequent calls.
func GetFactory() (*factory.Factory, error) {
	defaultFactoryOnce.Do(func() {
		defaultFactory, defaultFactoryErr = NewFactory()
	})
	return defaultFactory, defaultFactoryErr
}

// GenerateFindPetsResponse generates a mock response for GET /pets.
// ctx is an optional replacement context for controlling generated values.
func GenerateFindPetsResponse(ctx map[string]any) (*FindPetsResponseData, error) {
	f, err := GetFactory()
	if err != nil {
		return nil, err
	}
	res, err := f.Response("/pets", "GET", ctx)
	if err != nil {
		return nil, err
	}
	var body FindPetsResponse
	if err := api.UnmarshalResponseInto(res.Body, "application/json", &body); err != nil {
		return nil, err
	}
	return NewFindPetsResponseData(&body).WithHeaders(res.Headers), nil
}

// GenerateFindPetsResponseBody generates a mock response body for GET /pets.
// Returns just the typed body without headers or status.
// ctx is an optional replacement context for controlling generated values.
func GenerateFindPetsResponseBody(ctx map[string]any) (*FindPetsResponse, error) {
	res, err := GenerateFindPetsResponse(ctx)
	if err != nil {
		return nil, err
	}
	return res.Body, nil
}

// GenerateFindPetsRequest generates a mock request for GET /pets.
// ctx is an optional replacement context for controlling generated values.
func GenerateFindPetsRequest(ctx map[string]any) (schema.GeneratedRequest, error) {
	f, err := GetFactory()
	if err != nil {
		return schema.GeneratedRequest{}, err
	}
	return f.Request("/pets", "GET", ctx)
}

// GenerateAddPetResponse generates a mock response for POST /pets.
// ctx is an optional replacement context for controlling generated values.
func GenerateAddPetResponse(ctx map[string]any) (*AddPetResponseData, error) {
	f, err := GetFactory()
	if err != nil {
		return nil, err
	}
	res, err := f.Response("/pets", "POST", ctx)
	if err != nil {
		return nil, err
	}
	var body AddPetResponse
	if err := api.UnmarshalResponseInto(res.Body, "application/json", &body); err != nil {
		return nil, err
	}
	return NewAddPetResponseData(&body).WithHeaders(res.Headers), nil
}

// GenerateAddPetResponseBody generates a mock response body for POST /pets.
// Returns just the typed body without headers or status.
// ctx is an optional replacement context for controlling generated values.
func GenerateAddPetResponseBody(ctx map[string]any) (*AddPetResponse, error) {
	res, err := GenerateAddPetResponse(ctx)
	if err != nil {
		return nil, err
	}
	return res.Body, nil
}

// GenerateAddPetRequest generates a mock request for POST /pets.
// ctx is an optional replacement context for controlling generated values.
func GenerateAddPetRequest(ctx map[string]any) (schema.GeneratedRequest, error) {
	f, err := GetFactory()
	if err != nil {
		return schema.GeneratedRequest{}, err
	}
	return f.Request("/pets", "POST", ctx)
}

// GenerateAddPetRequestBody generates a typed mock request body for POST /pets.
// ctx is an optional replacement context for controlling generated values.
func GenerateAddPetRequestBody(ctx map[string]any) (*AddPetBody, error) {
	req, err := GenerateAddPetRequest(ctx)
	if err != nil {
		return nil, err
	}
	var body AddPetBody
	if err := json.Unmarshal(req.Body, &body); err != nil {
		return nil, err
	}
	return &body, nil
}

// GenerateFindPetByIDResponse generates a mock response for GET /pets/{id}.
// ctx is an optional replacement context for controlling generated values.
func GenerateFindPetByIDResponse(ctx map[string]any) (*FindPetByIDResponseData, error) {
	f, err := GetFactory()
	if err != nil {
		return nil, err
	}
	res, err := f.Response("/pets/{id}", "GET", ctx)
	if err != nil {
		return nil, err
	}
	var body FindPetByIDResponse
	if err := api.UnmarshalResponseInto(res.Body, "application/json", &body); err != nil {
		return nil, err
	}
	return NewFindPetByIDResponseData(&body).WithHeaders(res.Headers), nil
}

// GenerateFindPetByIDResponseBody generates a mock response body for GET /pets/{id}.
// Returns just the typed body without headers or status.
// ctx is an optional replacement context for controlling generated values.
func GenerateFindPetByIDResponseBody(ctx map[string]any) (*FindPetByIDResponse, error) {
	res, err := GenerateFindPetByIDResponse(ctx)
	if err != nil {
		return nil, err
	}
	return res.Body, nil
}

// GenerateFindPetByIDRequest generates a mock request for GET /pets/{id}.
// ctx is an optional replacement context for controlling generated values.
func GenerateFindPetByIDRequest(ctx map[string]any) (schema.GeneratedRequest, error) {
	f, err := GetFactory()
	if err != nil {
		return schema.GeneratedRequest{}, err
	}
	return f.Request("/pets/{id}", "GET", ctx)
}

// GenerateDeletePetResponse generates a mock response for DELETE /pets/{id}.
// ctx is an optional replacement context for controlling generated values.
func GenerateDeletePetResponse(ctx map[string]any) (*DeletePetResponseData, error) {
	f, err := GetFactory()
	if err != nil {
		return nil, err
	}
	res, err := f.Response("/pets/{id}", "DELETE", ctx)
	if err != nil {
		return nil, err
	}
	return NewDeletePetResponseData(nil).WithHeaders(res.Headers), nil
}

// GenerateDeletePetResponseBody generates a mock response body for DELETE /pets/{id}.
// Returns just the typed body without headers or status.
// ctx is an optional replacement context for controlling generated values.
func GenerateDeletePetResponseBody(ctx map[string]any) error {
	_, err := GenerateDeletePetResponse(ctx)
	return err
}

// GenerateDeletePetRequest generates a mock request for DELETE /pets/{id}.
// ctx is an optional replacement context for controlling generated values.
func GenerateDeletePetRequest(ctx map[string]any) (schema.GeneratedRequest, error) {
	f, err := GetFactory()
	if err != nil {
		return schema.GeneratedRequest{}, err
	}
	return f.Request("/pets/{id}", "DELETE", ctx)
}

type FindPetByIDPath struct {
	ID int64 `json:"id" validate:"required"`
}

func (f FindPetByIDPath) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(f))
}

type DeletePetPath struct {
	ID int64 `json:"id" validate:"required"`
}

func (d DeletePetPath) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(d))
}

type AddPetBody = NewPet

type FindPetsQuery struct {
	Tags  []string `json:"tags,omitempty"`
	Limit *int32   `json:"limit,omitempty"`
}

// FindPetsResponseData wraps the success response with optional headers and status override.
type FindPetsResponseData struct {
	Body    *FindPetsResponse
	Headers http.Header
	Status  int // 0 = use default (200)
}

// NewFindPetsResponseData creates a new FindPetsResponseData with the given body.
func NewFindPetsResponseData(body *FindPetsResponse) *FindPetsResponseData {
	return &FindPetsResponseData{Body: body}
}

// WithHeaders sets custom headers on the response.
func (r *FindPetsResponseData) WithHeaders(h http.Header) *FindPetsResponseData {
	r.Headers = h
	return r
}

// WithStatus overrides the default status code.
func (r *FindPetsResponseData) WithStatus(code int) *FindPetsResponseData {
	r.Status = code
	return r
}

// AddPetResponseData wraps the success response with optional headers and status override.
type AddPetResponseData struct {
	Body    *AddPetResponse
	Headers http.Header
	Status  int // 0 = use default (200)
}

// NewAddPetResponseData creates a new AddPetResponseData with the given body.
func NewAddPetResponseData(body *AddPetResponse) *AddPetResponseData {
	return &AddPetResponseData{Body: body}
}

// WithHeaders sets custom headers on the response.
func (r *AddPetResponseData) WithHeaders(h http.Header) *AddPetResponseData {
	r.Headers = h
	return r
}

// WithStatus overrides the default status code.
func (r *AddPetResponseData) WithStatus(code int) *AddPetResponseData {
	r.Status = code
	return r
}

// FindPetByIDResponseData wraps the success response with optional headers and status override.
type FindPetByIDResponseData struct {
	Body    *FindPetByIDResponse
	Headers http.Header
	Status  int // 0 = use default (200)
}

// NewFindPetByIDResponseData creates a new FindPetByIDResponseData with the given body.
func NewFindPetByIDResponseData(body *FindPetByIDResponse) *FindPetByIDResponseData {
	return &FindPetByIDResponseData{Body: body}
}

// WithHeaders sets custom headers on the response.
func (r *FindPetByIDResponseData) WithHeaders(h http.Header) *FindPetByIDResponseData {
	r.Headers = h
	return r
}

// WithStatus overrides the default status code.
func (r *FindPetByIDResponseData) WithStatus(code int) *FindPetByIDResponseData {
	r.Status = code
	return r
}

// DeletePetResponseData wraps the success response with optional headers and status override.
type DeletePetResponseData struct {
	Body    *struct{}
	Headers http.Header
	Status  int // 0 = use default (204)
}

// NewDeletePetResponseData creates a new DeletePetResponseData with the given body.
func NewDeletePetResponseData(body *struct{}) *DeletePetResponseData {
	return &DeletePetResponseData{Body: body}
}

// WithHeaders sets custom headers on the response.
func (r *DeletePetResponseData) WithHeaders(h http.Header) *DeletePetResponseData {
	r.Headers = h
	return r
}

// WithStatus overrides the default status code.
func (r *DeletePetResponseData) WithStatus(code int) *DeletePetResponseData {
	r.Status = code
	return r
}

type FindPetsResponse []Pet

func (f FindPetsResponse) Validate() error {
	if f == nil {
		return nil
	}
	var errors runtime.ValidationErrors
	for i, item := range f {
		if v, ok := any(item).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append(fmt.Sprintf("[%d]", i), err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

type FindPetsErrorResponse = Error

type AddPetResponse = Pet

type AddPetErrorResponse = Error

type FindPetByIDResponse = Pet

type FindPetByIDErrorResponse = Error

type DeletePetErrorResponse = Error

// FindPetsServiceRequestOptions holds all parameters for the FindPets operation.
type FindPetsServiceRequestOptions struct {
	Query *FindPetsQuery
	// RawRequest provides access to the underlying HTTP request for custom content type handling.
	RawRequest *http.Request
	// GenerateResponse generates a sample response with random data satisfying the OpenAPI schema.
	GenerateResponse func() (*FindPetsResponseData, error)
}

// Validate validates all the fields in the options.
func (o *FindPetsServiceRequestOptions) Validate() error {
	var errors runtime.ValidationErrors

	if o.Query != nil {
		if v, ok := any(o.Query).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("Query", err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}

	return errors
}

// AddPetServiceRequestOptions holds all parameters for the AddPet operation.
type AddPetServiceRequestOptions struct {
	Body *AddPetBody
	// RawRequest provides access to the underlying HTTP request for custom content type handling.
	RawRequest *http.Request
	// GenerateResponse generates a sample response with random data satisfying the OpenAPI schema.
	GenerateResponse func() (*AddPetResponseData, error)
}

// Validate validates all the fields in the options.
func (o *AddPetServiceRequestOptions) Validate() error {
	var errors runtime.ValidationErrors

	if o.Body != nil {
		if v, ok := any(o.Body).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("Body", err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}

	return errors
}

// FindPetByIDServiceRequestOptions holds all parameters for the FindPetByID operation.
type FindPetByIDServiceRequestOptions struct {
	PathParams *FindPetByIDPath
	// RawRequest provides access to the underlying HTTP request for custom content type handling.
	RawRequest *http.Request
	// GenerateResponse generates a sample response with random data satisfying the OpenAPI schema.
	GenerateResponse func() (*FindPetByIDResponseData, error)
}

// Validate validates all the fields in the options.
func (o *FindPetByIDServiceRequestOptions) Validate() error {
	var errors runtime.ValidationErrors

	if o.PathParams != nil {
		if v, ok := any(o.PathParams).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("PathParams", err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}

	return errors
}

// DeletePetServiceRequestOptions holds all parameters for the DeletePet operation.
type DeletePetServiceRequestOptions struct {
	PathParams *DeletePetPath
	// RawRequest provides access to the underlying HTTP request for custom content type handling.
	RawRequest *http.Request
	// GenerateResponse generates a sample response with random data satisfying the OpenAPI schema.
	GenerateResponse func() (*DeletePetResponseData, error)
}

// Validate validates all the fields in the options.
func (o *DeletePetServiceRequestOptions) Validate() error {
	var errors runtime.ValidationErrors

	if o.PathParams != nil {
		if v, ok := any(o.PathParams).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("PathParams", err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}

	return errors
}

type Pet struct {
	Name string  `json:"name" validate:"required"`
	Tag  *string `json:"tag,omitempty"`
	ID   int64   `json:"id" validate:"required"`
}

func (p Pet) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(p))
}

type NewPet struct {
	Name string  `json:"name" validate:"required"`
	Tag  *string `json:"tag,omitempty"`
}

func (n NewPet) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(n))
}

type Error struct {
	Code    int32  `json:"code" validate:"required"`
	Message string `json:"message" validate:"required"`
}

func (e Error) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(e))
}

func (s Error) Error() string {
	return "unmapped client error"
}

var typesValidator *validator.Validate

func init() {
	typesValidator = validator.New(validator.WithRequiredStructEnabled())
	runtime.RegisterCustomTypeFunc(typesValidator)
}
