// Code generated by mockzilla-codegen. DO NOT EDIT.

package petstore

import (
	"context"
	"embed"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"log/slog"
	"net/http"
	"sync"

	chi "github.com/go-chi/chi/v5"
	"github.com/mockzilla/mockzilla/v2/pkg/api"
	"github.com/mockzilla/mockzilla/v2/pkg/config"
	"github.com/mockzilla/mockzilla/v2/pkg/db"
	"github.com/mockzilla/mockzilla/v2/pkg/factory"
	"github.com/mockzilla/mockzilla/v2/pkg/generator"
	"github.com/mockzilla/mockzilla/v2/pkg/loader"
	"github.com/mockzilla/mockzilla/v2/pkg/schema"
	"github.com/mockzilla/mockzilla/v2/pkg/typedef"
)

//go:embed setup/config.yml
var configSrc []byte

//go:embed setup/openapi.*
var openapiSpecFS embed.FS

//go:embed setup/context.yml
var contextSrc []byte

// ServiceErrorHandler answers the requests that fail before the service is reached.
var ServiceErrorHandler ErrorHandler = DefaultErrorHandler{}

// cfg is set before any init function runs, so the package's other files can read it in theirs.
var cfg, cfgErr = config.NewServiceConfigFromBytes(configSrc)

func init() {
	if cfgErr != nil {
		slog.Error("Failed to parse service config", "error", cfgErr)
		return
	}
	loader.Register(cfg.Name, RegisterAPIRouter)
}

// RegisterAPIRouter registers the service with the central router.
func RegisterAPIRouter(router *api.Router) {
	serviceName := cfg.Name

	openapiSpec, err := api.ReadEmbeddedSpec(openapiSpecFS)
	if err != nil {
		slog.Error(fmt.Sprintf("Failed to read OpenAPI spec for %s", serviceName), "error", err, "service", serviceName)
		return
	}

	registry, err := typedef.NewRegistry(openapiSpec, typedef.RegistryOptions{
		SpecOptions:     cfg.SpecOptions,
		ReleaseDocument: true,
	})
	if err != nil {
		slog.Error(fmt.Sprintf("Failed to create registry for %s", serviceName), "error", err, "service", serviceName)
		return
	}

	orderedCtx := router.ServiceContext(serviceName, contextSrc)
	gen, err := generator.NewGenerator(orderedCtx, router.GetContexts())
	if err != nil {
		slog.Error(fmt.Sprintf("Failed to create generator for %s", serviceName), "error", err, "service", serviceName)
		return
	}

	router.RegisterHTTPHandler(cfg, func(serviceDB db.DB) api.Handler {
		userSvc := newService(&api.ServiceParams{
			AppConfig:     router.Config(),
			ServiceConfig: cfg,
			DB:            serviceDB,
		})
		genSvc := &generatorService{service: userSvc, generator: gen, registry: registry}
		return newServiceHandler(genSvc, gen, registry)
	})

	slog.Info(fmt.Sprintf("Registered %s service", serviceName), "service", serviceName)
}

type serviceHandler struct {
	router   chi.Router
	gen      generator.Generate
	registry typedef.OperationRegistry
}

func newServiceHandler(svc ServiceInterface, gen generator.Generate, registry typedef.OperationRegistry) api.Handler {
	return &serviceHandler{
		router: NewRouter(svc,
			WithMiddleware(api.ContextReplacementsMiddleware),
			WithErrorHandler(returnedErrors{next: ServiceErrorHandler}),
		),
		gen:      gen,
		registry: registry,
	}
}

func (h *serviceHandler) Routes() api.RouteDescriptions {
	routes := h.router.Routes()
	descriptions := make(api.RouteDescriptions, 0, len(routes))
	for _, route := range routes {
		for method := range route.Handlers {
			descriptions = append(descriptions, &api.RouteDescription{Method: method, Path: route.Pattern})
		}
	}
	return descriptions
}

func (h *serviceHandler) RegisterRoutes(router chi.Router) {
	router.Mount("/", h.router)
}

func (h *serviceHandler) Generate(w http.ResponseWriter, r *http.Request) {
	var req api.GenerateRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		message := err.Error()
		if errors.Is(err, io.EOF) {
			message = "request body is empty or incomplete"
		}
		slog.Error("Failed to decode request", "error", err)
		http.Error(w, message, http.StatusBadRequest)
		return
	}

	op := h.registry.FindOperation(req.Path, req.Method)
	res := h.gen.Request(&req, op, req.Context)
	api.NewJSONResponse(w).Send(res)
}

// returnedError is an error the service returned, with the status of the response it returned too.
// It has no Unwrap, so the adapter cannot answer an error type of the spec before returnedErrors.
type returnedError struct {
	status int
	err    error
}

func (e *returnedError) Error() string {
	return e.err.Error()
}

// returnedErrors hands next an error the service returned as it was returned, with the status of
// its response, so a service answers an error with the status it sets.
type returnedErrors struct {
	next ErrorHandler
}

func (h returnedErrors) HandleError(w http.ResponseWriter, r *http.Request, status int, err error) {
	var returned *returnedError
	if errors.As(err, &returned) {
		if returned.status != 0 {
			status = returned.status
		}
		err = returned.err
	}
	h.next.HandleError(w, r, status, err)
}

// generatorService calls the service first and makes a mock response when it returns nil, nil.
type generatorService struct {
	service   *service
	generator generator.Generate
	registry  typedef.OperationRegistry
}

var _ ServiceInterface = (*generatorService)(nil)

func (s *generatorService) FindPets(ctx context.Context, opts *FindPetsServiceRequestOptions) (*FindPetsResponseData, error) {
	opts.GenerateResponse = func() (*FindPetsResponseData, error) {
		respSchema := s.registry.GetResponseSchema("/pets", "GET")
		res := s.generator.Response(respSchema, api.UserContextFromGoContext(ctx), generator.WithRequest(opts.RawRequest))
		var body FindPetsResponse200
		if err := api.UnmarshalResponseInto(res.Body, "application/json", &body); err != nil {
			return nil, err
		}
		return NewFindPetsResponseData200(body).WithHeaders(res.Headers), nil
	}

	resp, err := s.service.FindPets(ctx, opts)
	if err != nil {
		status := 0
		if resp != nil {
			status = resp.Status
		}
		return nil, &returnedError{status: status, err: err}
	}
	if resp != nil {
		return resp, nil
	}
	return opts.GenerateResponse()
}

func (s *generatorService) AddPet(ctx context.Context, opts *AddPetServiceRequestOptions) (*AddPetResponseData, error) {
	opts.GenerateResponse = func() (*AddPetResponseData, error) {
		respSchema := s.registry.GetResponseSchema("/pets", "POST")
		res := s.generator.Response(respSchema, api.UserContextFromGoContext(ctx), generator.WithRequest(opts.RawRequest))
		var body Pet
		if err := api.UnmarshalResponseInto(res.Body, "application/json", &body); err != nil {
			return nil, err
		}
		return NewAddPetResponseData200(&body).WithHeaders(res.Headers), nil
	}

	resp, err := s.service.AddPet(ctx, opts)
	if err != nil {
		status := 0
		if resp != nil {
			status = resp.Status
		}
		return nil, &returnedError{status: status, err: err}
	}
	if resp != nil {
		return resp, nil
	}
	return opts.GenerateResponse()
}

func (s *generatorService) FindPetByID(ctx context.Context, opts *FindPetByIDServiceRequestOptions) (*FindPetByIDResponseData, error) {
	opts.GenerateResponse = func() (*FindPetByIDResponseData, error) {
		respSchema := s.registry.GetResponseSchema("/pets/{id}", "GET")
		res := s.generator.Response(respSchema, api.UserContextFromGoContext(ctx), generator.WithRequest(opts.RawRequest))
		var body Pet
		if err := api.UnmarshalResponseInto(res.Body, "application/json", &body); err != nil {
			return nil, err
		}
		return NewFindPetByIDResponseData200(&body).WithHeaders(res.Headers), nil
	}

	resp, err := s.service.FindPetByID(ctx, opts)
	if err != nil {
		status := 0
		if resp != nil {
			status = resp.Status
		}
		return nil, &returnedError{status: status, err: err}
	}
	if resp != nil {
		return resp, nil
	}
	return opts.GenerateResponse()
}

func (s *generatorService) DeletePet(ctx context.Context, opts *DeletePetServiceRequestOptions) (*DeletePetResponseData, error) {
	opts.GenerateResponse = func() (*DeletePetResponseData, error) {
		respSchema := s.registry.GetResponseSchema("/pets/{id}", "DELETE")
		res := s.generator.Response(respSchema, api.UserContextFromGoContext(ctx), generator.WithRequest(opts.RawRequest))
		return NewDeletePetResponseData204().WithHeaders(res.Headers), nil
	}

	resp, err := s.service.DeletePet(ctx, opts)
	if err != nil {
		status := 0
		if resp != nil {
			status = resp.Status
		}
		return nil, &returnedError{status: status, err: err}
	}
	if resp != nil {
		return resp, nil
	}
	return opts.GenerateResponse()
}

var (
	defaultFactory     *factory.Factory
	defaultFactoryOnce sync.Once
	defaultFactoryErr  error
)

// NewFactory returns a Factory with the spec, spec options and context of this service.
func NewFactory(opts ...factory.FactoryOption) (*factory.Factory, error) {
	openapiSpec, err := api.ReadEmbeddedSpec(openapiSpecFS)
	if err != nil {
		return nil, err
	}

	allOpts := []factory.FactoryOption{factory.WithServiceContext(contextSrc)}
	if cfg != nil && cfg.SpecOptions != nil {
		allOpts = append(allOpts, factory.WithSpecOptions(cfg.SpecOptions))
	}
	allOpts = append(allOpts, opts...)
	return factory.NewFactory(openapiSpec, allOpts...)
}

// GetFactory returns the Factory of this service, made on the first call.
func GetFactory() (*factory.Factory, error) {
	defaultFactoryOnce.Do(func() {
		defaultFactory, defaultFactoryErr = NewFactory()
	})
	return defaultFactory, defaultFactoryErr
}

// GenerateFindPetsResponse makes a mock response for GET /pets.
func GenerateFindPetsResponse(ctx map[string]any) (*FindPetsResponseData, error) {
	f, err := GetFactory()
	if err != nil {
		return nil, err
	}
	res, err := f.Response("/pets", "GET", ctx)
	if err != nil {
		return nil, err
	}
	var body FindPetsResponse200
	if err := api.UnmarshalResponseInto(res.Body, "application/json", &body); err != nil {
		return nil, err
	}
	return NewFindPetsResponseData200(body).WithHeaders(res.Headers), nil
}

// GenerateFindPetsRequest makes a mock request for GET /pets.
func GenerateFindPetsRequest(ctx map[string]any) (schema.GeneratedRequest, error) {
	f, err := GetFactory()
	if err != nil {
		return schema.GeneratedRequest{}, err
	}
	return f.Request("/pets", "GET", ctx)
}

// GenerateAddPetResponse makes a mock response for POST /pets.
func GenerateAddPetResponse(ctx map[string]any) (*AddPetResponseData, error) {
	f, err := GetFactory()
	if err != nil {
		return nil, err
	}
	res, err := f.Response("/pets", "POST", ctx)
	if err != nil {
		return nil, err
	}
	var body Pet
	if err := api.UnmarshalResponseInto(res.Body, "application/json", &body); err != nil {
		return nil, err
	}
	return NewAddPetResponseData200(&body).WithHeaders(res.Headers), nil
}

// GenerateAddPetRequest makes a mock request for POST /pets.
func GenerateAddPetRequest(ctx map[string]any) (schema.GeneratedRequest, error) {
	f, err := GetFactory()
	if err != nil {
		return schema.GeneratedRequest{}, err
	}
	return f.Request("/pets", "POST", ctx)
}

// GenerateAddPetRequestBody makes a typed mock request body for POST /pets.
func GenerateAddPetRequestBody(ctx map[string]any) (*NewPet, error) {
	req, err := GenerateAddPetRequest(ctx)
	if err != nil {
		return nil, err
	}
	body := new(NewPet)
	if err := json.Unmarshal(req.Body, body); err != nil {
		return nil, err
	}
	return body, nil
}

// GenerateFindPetByIDResponse makes a mock response for GET /pets/{id}.
func GenerateFindPetByIDResponse(ctx map[string]any) (*FindPetByIDResponseData, error) {
	f, err := GetFactory()
	if err != nil {
		return nil, err
	}
	res, err := f.Response("/pets/{id}", "GET", ctx)
	if err != nil {
		return nil, err
	}
	var body Pet
	if err := api.UnmarshalResponseInto(res.Body, "application/json", &body); err != nil {
		return nil, err
	}
	return NewFindPetByIDResponseData200(&body).WithHeaders(res.Headers), nil
}

// GenerateFindPetByIDRequest makes a mock request for GET /pets/{id}.
func GenerateFindPetByIDRequest(ctx map[string]any) (schema.GeneratedRequest, error) {
	f, err := GetFactory()
	if err != nil {
		return schema.GeneratedRequest{}, err
	}
	return f.Request("/pets/{id}", "GET", ctx)
}

// GenerateDeletePetResponse makes a mock response for DELETE /pets/{id}.
func GenerateDeletePetResponse(ctx map[string]any) (*DeletePetResponseData, error) {
	f, err := GetFactory()
	if err != nil {
		return nil, err
	}
	res, err := f.Response("/pets/{id}", "DELETE", ctx)
	if err != nil {
		return nil, err
	}
	return NewDeletePetResponseData204().WithHeaders(res.Headers), nil
}

// GenerateDeletePetRequest makes a mock request for DELETE /pets/{id}.
func GenerateDeletePetRequest(ctx map[string]any) (schema.GeneratedRequest, error) {
	f, err := GetFactory()
	if err != nil {
		return schema.GeneratedRequest{}, err
	}
	return f.Request("/pets/{id}", "DELETE", ctx)
}
