# yaml-language-server: $schema=https://raw.githubusercontent.com/mockzilla/mockzilla/refs/heads/master/resources/json-schema-service.json
name: petstore
latency: 0ms
cache:
  requests: true
#upstream:
#  url: https://petstore3.swagger.io/api/v3
#  timeout: 10s
