// Code generated by mockzilla. DO NOT EDIT.

package main

import (
	_ "github.com/mockzilla/mockzilla-codegen-template/pkg/hello_world"
	_ "github.com/mockzilla/mockzilla-codegen-template/pkg/petstore"
)
