// Code generated by connexions. DO NOT EDIT.

package main

import (
	_ "github.com/mockzilla/connexions-codegen-template/pkg/hello_world"
	_ "github.com/mockzilla/connexions-codegen-template/pkg/petstore"
)
